"""init

Revision ID: 217c8571ee06
Revises: 4aef81a6fad9
Create Date: 2025-06-16 20:58:49.607205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '217c8571ee06'
down_revision: Union[str, None] = '4aef81a6fad9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charlie', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('charlie', sa.Column('description_ENG', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('charlie', 'description_ENG')
    op.drop_column('charlie', 'description')
    # ### end Alembic commands ###
