"""init

Revision ID: 4aef81a6fad9
Revises: 
Create Date: 2025-06-16 20:54:52.713416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aef81a6fad9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('label_ENG', sa.Text(), nullable=True),
    sa.Column('number', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_achievement'))
    )
    op.create_table('admin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin'))
    )
    op.create_table('bubble',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_ENG', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('tag_ENG', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bubble'))
    )
    op.create_table('charlie',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('name_ENG', sa.Text(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('motto', sa.JSON(), nullable=True),
    sa.Column('motto_ENG', sa.JSON(), nullable=True),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('resume', sa.Text(), nullable=True),
    sa.Column('visitorNumber', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_charlie'))
    )
    op.create_table('growth_timeline',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_ENG', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_growth_timeline'))
    )
    op.create_table('passage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_ENG', sa.Text(), nullable=True),
    sa.Column('timeCreated', sa.DateTime(), nullable=True),
    sa.Column('timeLastUpdated', sa.DateTime(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('tag_ENG', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_passage'))
    )
    op.create_table('talent',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('title_ENG', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_ENG', sa.Text(), nullable=True),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_talent'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('talent')
    op.drop_table('passage')
    op.drop_table('growth_timeline')
    op.drop_table('charlie')
    op.drop_table('bubble')
    op.drop_table('admin')
    op.drop_table('achievement')
    # ### end Alembic commands ###
