"""init

Revision ID: 4c51474cf1d4
Revises: 1bdcd277394e
Create Date: 2025-06-17 11:26:20.772160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '4c51474cf1d4'
down_revision: Union[str, None] = '1bdcd277394e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_ENG', sa.Text(), nullable=True),
    sa.Column('timeCreated', sa.DateTime(), nullable=True),
    sa.Column('timeLastUpdated', sa.DateTime(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('tag_ENG', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article'))
    )
    op.drop_table('passage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passage',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('content_ENG', sa.TEXT(), nullable=True),
    sa.Column('timeCreated', sa.DATETIME(), nullable=True),
    sa.Column('timeLastUpdated', sa.DATETIME(), nullable=True),
    sa.Column('tags', sqlite.JSON(), nullable=True),
    sa.Column('tag_ENG', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_passage')
    )
    op.drop_table('article')
    # ### end Alembic commands ###
