"""m

Revision ID: 599dc70a717f
Revises: 2b45473570b0
Create Date: 2025-06-26 16:47:21.968791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '599dc70a717f'
down_revision: Union[str, None] = '2b45473570b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('isReleased', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'isReleased')
    # ### end Alembic commands ###
