"""m

Revision ID: 684c5542895e
Revises: 792b3312ad9c
Create Date: 2025-06-27 22:48:49.416681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '684c5542895e'
down_revision: Union[str, None] = '792b3312ad9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('talent', sa.Column('gotoUrl', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('talent', 'gotoUrl')
    # ### end Alembic commands ###
