"""init

Revision ID: 7cca10ff70dd
Revises: 217c8571ee06
Create Date: 2025-06-16 21:05:50.581546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cca10ff70dd'
down_revision: Union[str, None] = '217c8571ee06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charlie', sa.Column('github', sa.Text(), nullable=True))
    op.add_column('charlie', sa.Column('email', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('charlie', 'email')
    op.drop_column('charlie', 'github')
    # ### end Alembic commands ###
