"""m

Revision ID: 98ba519eb2da
Revises: 684c5542895e
Create Date: 2025-06-28 15:19:16.263264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98ba519eb2da'
down_revision: Union[str, None] = '684c5542895e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fingerprint',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fingerprint', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fingerprint'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fingerprint')
    # ### end Alembic commands ###
