"""m

Revision ID: acedb14ea235
Revises: 98ba519eb2da
Create Date: 2025-06-28 17:27:12.930363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acedb14ea235'
down_revision: Union[str, None] = '98ba519eb2da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fingerprint', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fingerprint', 'create_time')
    # ### end Alembic commands ###
