"""empty message

Revision ID: 18c576dba598
Revises: acedb14ea235
Create Date: 2025-07-16 21:14:02.485530

"""

# revision identifiers, used by Alembic.
revision = '18c576dba598'
down_revision = 'acedb14ea235'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place_beent_to',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('country_ENG', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('city_ENG', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_ENG', sa.Text(), nullable=True),
    sa.Column('dateStart', sa.Date(), nullable=True),
    sa.Column('dateEnd', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_place_beent_to'))
    )
    op.create_table('travel_photo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('travelId', sa.Integer(), nullable=True),
    sa.Column('isShown', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['travelId'], ['place_beent_to.id'], name=op.f('fk_travel_photo_travelId_place_beent_to')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_travel_photo'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('travel_photo')
    op.drop_table('place_beent_to')
    # ### end Alembic commands ###