"""m

Revision ID: 9e5927639050
Revises: e17cc8215755
Create Date: 2025-07-23 10:42:24.860896

"""

# revision identifiers, used by Alembic.
revision = '9e5927639050'
down_revision = 'e17cc8215755'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('label_ENG', sa.Text(), nullable=True),
    sa.Column('number', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_achievement'))
    )
    op.create_table('admin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin'))
    )
    op.create_table('article',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_ENG', sa.Text(), nullable=True),
    sa.Column('timeCreated', sa.DateTime(), nullable=True),
    sa.Column('timeLastUpdated', sa.DateTime(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('tag_ENG', sa.JSON(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('isReleased', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article'))
    )
    op.create_table('bubble',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_ENG', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('tag_ENG', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bubble'))
    )
    op.create_table('charlie',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('name_ENG', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_ENG', sa.Text(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('github', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('motto', sa.JSON(), nullable=True),
    sa.Column('motto_ENG', sa.JSON(), nullable=True),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('resume', sa.Text(), nullable=True),
    sa.Column('visitorNumber', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_charlie'))
    )
    op.create_table('fingerprint',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fingerprint', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fingerprint'))
    )
    op.create_table('growth_timeline',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_ENG', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_growth_timeline'))
    )
    op.create_table('place_been_to',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('country_ENG', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('city_ENG', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_ENG', sa.Text(), nullable=True),
    sa.Column('dateStart', sa.Date(), nullable=True),
    sa.Column('dateEnd', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_place_been_to'))
    )
    op.create_table('talent',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('title_ENG', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_ENG', sa.Text(), nullable=True),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.Column('gotoUrl', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_talent'))
    )
    op.create_table('travel_photo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('travelId', sa.Integer(), nullable=True),
    sa.Column('isShown', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['travelId'], ['place_been_to.id'], name=op.f('fk_travel_photo_travelId_place_been_to')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_travel_photo'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('travel_photo')
    op.drop_table('talent')
    op.drop_table('place_been_to')
    op.drop_table('growth_timeline')
    op.drop_table('fingerprint')
    op.drop_table('charlie')
    op.drop_table('bubble')
    op.drop_table('article')
    op.drop_table('admin')
    op.drop_table('achievement')
    # ### end Alembic commands ###