"""m

Revision ID: b4583bdfb0a8
Revises: e17cc8215755
Create Date: 2025-07-22 19:05:35.144937

"""

# revision identifiers, used by Alembic.
revision = 'b4583bdfb0a8'
down_revision = 'e17cc8215755'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place_been_to',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('country_ENG', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('city_ENG', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_ENG', sa.Text(), nullable=True),
    sa.Column('dateStart', sa.Date(), nullable=True),
    sa.Column('dateEnd', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_place_been_to'))
    )
    op.drop_table('place_beent_to')
    with op.batch_alter_table('travel_photo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_travel_photo_travelId_place_been_to'), 'place_been_to', ['travelId'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('travel_photo', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_travel_photo_travelId_place_been_to'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'place_beent_to', ['travelId'], ['id'])

    op.create_table('place_beent_to',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('country', sa.TEXT(), nullable=True),
    sa.Column('country_ENG', sa.TEXT(), nullable=True),
    sa.Column('city', sa.TEXT(), nullable=True),
    sa.Column('city_ENG', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('description_ENG', sa.TEXT(), nullable=True),
    sa.Column('dateStart', sa.DATE(), nullable=True),
    sa.Column('dateEnd', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_place_beent_to'))
    )
    op.drop_table('place_been_to')
    # ### end Alembic commands ###